import { config } from "./app-config.js";

export const state = {
  defaultTextures: [],
  faceTextures: [],
  isLoadingLocal: false,
  selectedDataUrls: [],
  frostedTexture: null,
  textureCache: new Map(),
  nftInventory: [],
  nftSelection: [],
  nftStatus: "idle",
  nftError: null,
  sumFloorEth: 0,
  floorSnapshotAt: null,
  bgImage: null,
  bgImageDataUrl: null,
  rotX: -0.35,
  rotY: 0.65,
  rotVelX: 0,
  rotVelY: 0,
  isDragging: false,
  zoom: config.zoom.initial,
  backdrop: null,
  edgePasses: [],
  lastMouse: null,
  pinchStartDist: null,
  pinchStartZoom: null,
};
